// Generated by CoffeeScript 1.12.7
(function() {
  var DeLorean, Tardis, TimeMachine, another_full_name, days, doc_browns_wheels, doctors_wife, first_name, full_name, giveKudos, greeting, initialize_time_circuits, initialize_time_circuits_2, initialize_time_circuits_3, ip, mcflys, multiples, num, ref, ref1, speed, teachers, teachers2, time_machine, tuesday_to_friday, users, woah, year,
    slice = [].slice,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  year = 1985;

  speed = 88;

  first_name = "Marty";

  full_name = first_name + " McFly";

  another_full_name = first_name + " McFly";

  initialize_time_circuits = function() {
    return year * flux_capacitor_constant * speed;
  };

  initialize_time_circuits_2 = function() {
    year = 1885;
    return year * flux_capacitor_constant * speed;
  };

  initialize_time_circuits_3 = function(speed, year) {
    if (year == null) {
      year = 1885;
    }
    return year * flux_capacitor_constant * speed;
  };

  initialize_time_circuits_3(88);

  initialize_time_circuits_3(99);

  mcflys = ["Marty", "George", "Lorraine", "Dave", "Linda"];

  woah = [0, 1, 9, 6, 5, 4, 8, 0, 0];

  teachers = {
    teacher: {
      name: "Andrew Chalkley",
      hair: "Ginger"
    },
    teacher: {
      name: "Jim Hoskins",
      hair: "Ginger"
    },
    teacher: {
      name: "Pasan Premaratne",
      hair: "Black"
    }
  };

  teachers2 = {
    teacher: {
      name: "Andrew Chalkley",
      hair: "Ginger"
    },
    teacher: {
      name: "Jim Hoskins",
      hair: "Ginger"
    },
    teacher: {
      name: "Pasan Premaratne",
      hair: "Black"
    }
  };

  days = [1, 2, 3, 4, 5, 6, 7];

  tuesday_to_friday = days.slice(1, 5);

  [].splice.apply(days, [1, 4].concat(ref = ["Tuesday", "Wednesday", "Thursday", "Friday"])), ref;

  giveKudos = function() {
    var first, rest, second, third;
    first = arguments[0], second = arguments[1], third = arguments[2], rest = 4 <= arguments.length ? slice.call(arguments, 3) : [];
    addKudosToUser(first, 10);
    addKudosToUser(second, 6);
    return addKudosToUser(third, 2);
  };

  users = ["Pasan", "Amit", "Jim", "Andrew", "Allison", "Jason", "A.J."];

  giveKudos.apply(null, users);

  TimeMachine = (function() {
    function TimeMachine() {}

    return TimeMachine;

  })();

  time_machine = new TimeMachine;

  TimeMachine = (function() {
    function TimeMachine(pilot) {
      this.pilot = pilot;
    }

    return TimeMachine;

  })();

  time_machine = new TimeMachine("H. G. Wells");

  console.log(time_machine.pilot);

  TimeMachine = (function() {
    function TimeMachine(pilot1) {
      this.pilot = pilot1;
    }

    return TimeMachine;

  })();

  Tardis = (function(superClass) {
    extend(Tardis, superClass);

    function Tardis() {
      return Tardis.__super__.constructor.apply(this, arguments);
    }

    return Tardis;

  })(TimeMachine);

  DeLorean = (function(superClass) {
    extend(DeLorean, superClass);

    function DeLorean() {
      return DeLorean.__super__.constructor.apply(this, arguments);
    }

    return DeLorean;

  })(TimeMachine);

  TimeMachine = (function() {
    function TimeMachine(pilot1) {
      this.pilot = pilot1;
    }

    TimeMachine.prototype.go = function(noise) {
      return console.log(noise);
    };

    return TimeMachine;

  })();

  Tardis = (function(superClass) {
    extend(Tardis, superClass);

    function Tardis() {
      return Tardis.__super__.constructor.apply(this, arguments);
    }

    Tardis.prototype.go = function() {
      return Tardis.__super__.go.call(this, "vorp vorp");
    };

    return Tardis;

  })(TimeMachine);

  DeLorean = (function(superClass) {
    extend(DeLorean, superClass);

    function DeLorean() {
      return DeLorean.__super__.constructor.apply(this, arguments);
    }

    DeLorean.prototype.go = function() {
      return DeLorean.__super__.go.call(this, "One point twenty-one gigawatts!");
    };

    return DeLorean;

  })(TimeMachine);

  doctors_wife = new Tardis("The Doctor");

  doc_browns_wheels = new DeLorean("Marty");

  doctors_wife.go();

  doc_browns_wheels.go();

  if (typeof user === "undefined" || user === null) {
    login();
  }

  if (year == null) {
    year = 1885;
  }

  greeting = typeof message !== "undefined" && message !== null ? message : "Hello, World!";

  ip = typeof securitySystem.lastUser === "function" ? (ref1 = securitySystem.lastUser().remoteSystem) != null ? ref1.ipAddress : void 0 : void 0;

  multiples = (function() {
    var i, results;
    results = [];
    for (num = i = 0; i <= 10; num = ++i) {
      results.push(num * 10);
    }
    return results;
  })();

}).call(this);
